"""Adicionando cidade_id em registros_materiais

Revision ID: b2c3408c9d1e
Revises: 
Create Date: 2025-06-14 12:14:37.330263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3408c9d1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_materiais', schema=None) as batch_op:
        batch_op.alter_column('atividade',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_materiais', schema=None) as batch_op:
        batch_op.alter_column('atividade',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
