"""Adiciona cidade_id a RegistroMaterial

Revision ID: cfe16f54b7a4
Revises: b2c3408c9d1e
Create Date: 2025-06-14 12:19:38.729511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe16f54b7a4'
down_revision = 'b2c3408c9d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_materiais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'cidades', ['cidade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_materiais', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cidade_id')

    # ### end Alembic commands ###
